# Imports a design bundle exported from Claude Design into the app.
#
#   bin/rails "design:import[C:/path/to/School Building Selector.html]"
#
# The export is a self-contained bundle: a JSON manifest of base64 assets, a
# list of external CDN resources, and the page template with asset UUIDs where
# URLs should be. At runtime the bundle's own loader mints blob URLs for those
# assets. This task does the same job ahead of time — it writes the assets to
# public/design/ and rewrites the UUID references to point at them — so Rails
# can serve the design directly, unchanged.
#
# Re-run it whenever the design is updated; everything it writes is generated.

require "json"
require "base64"
require "zlib"
require "stringio"

namespace :design do
  desc "Import a Claude Design export into public/design/ and app/views/selector/"
  task :import, [:path] => :environment do |_t, args|
    source = args[:path] or abort "Usage: bin/rails \"design:import[path/to/export.html]\""
    abort "Not found: #{source}" unless File.exist?(source)

    lines = File.readlines(source, encoding: "UTF-8")
    section = lambda do |type|
      idx = lines.index { |l| l.include?(%(<script type="__bundler/#{type}">)) }
      idx ? JSON.parse(lines[idx + 1]) : nil
    end

    manifest = section.call("manifest") or abort "No manifest in bundle"
    template = section.call("template") or abort "No template in bundle"
    ext_resources = section.call("ext_resources") || []

    out_dir = Rails.root.join("public", "design")
    FileUtils.rm_rf(out_dir)
    FileUtils.mkdir_p(out_dir)

    extensions = {
      "image/png" => "png", "image/jpeg" => "jpg", "image/svg+xml" => "svg",
      "image/webp" => "webp", "font/woff2" => "woff2", "font/woff" => "woff",
      "application/javascript" => "js", "text/javascript" => "js",
      "text/css" => "css", "text/html" => "html"
    }

    urls = {}
    manifest.each do |uuid, entry|
      bytes = Base64.decode64(entry["data"])
      bytes = Zlib::GzipReader.new(StringIO.new(bytes)).read if entry["compressed"]
      ext = extensions[entry["mime"]] || entry["mime"].to_s.split("/").last.presence || "bin"
      File.binwrite(out_dir.join("#{uuid}.#{ext}"), bytes)
      urls[uuid] = "/design/#{uuid}.#{ext}"
    end
    puts "Wrote #{manifest.size} assets to public/design/"

    # The template carries bare asset UUIDs wherever a URL belongs.
    urls.each { |uuid, url| template = template.gsub(uuid, url) }

    # The bundle's loader normally injects this map so the runtime resolves CDN
    # scripts (React, ReactDOM) to bundled copies instead of the network.
    resource_map = ext_resources.each_with_object({}) do |entry, map|
      local = urls[entry["uuid"]]
      map[entry["id"]] = local if local
    end
    injection = %(<script>window.__resources = #{JSON.generate(resource_map).gsub("</", "<\\/")};</script>)
    template = template.sub(/<head[^>]*>/i) { |tag| tag + injection }
    puts "Mapped #{resource_map.size} external resources to local copies"

    view_dir = Rails.root.join("app", "views", "selector")
    FileUtils.mkdir_p(view_dir)
    header = "<%# Generated by `rails design:import` from #{File.basename(source)} — do not edit. %>\n"
    File.write(view_dir.join("show.html.erb"), header + template, encoding: "UTF-8")
    puts "Wrote app/views/selector/show.html.erb (#{template.bytesize} bytes)"
  end
end
