class SelectorController < ApplicationController
  # Serves the imported design as-is. The view is a complete HTML document
  # generated by `rails design:import`, so it renders without the app layout.
  def show
    render layout: false
  end
end
